<?php

use GraphQL\Error\InvariantViolation;
use Illuminate\Support\Facades\Artisan;
use Nuwave\Lighthouse\Schema\SchemaBuilder;

function printGeneratedSchema(): string
{
    Artisan::call('lighthouse:print-schema');

    return Artisan::output();
}

it('prints the schema generated by LaraQL and the hand written SDL together', function () {
    $schema = printGeneratedSchema();

    expect($schema)
        // Hand written SDL is merged, not replaced.
        ->toContain('type SearchHit')
        ->toContain('enum ArticleStatus')
        ->toContain('handWrittenPing: String')
        // Types, inputs and paginators generated from models and attributes.
        ->toContain('type Article')
        ->toContain('input ArticleInput')
        ->toContain('type DeepArticle')
        ->toContain('type ArticleStats')
        ->toContain('type ArticleStatsPaginator')
        ->toContain('input SummaryFilterInput')
        ->toContain('input ArticleFilterInput')
        // Scalars shipped by LaraQL and the Scout integration.
        ->toContain('scalar Upload')
        ->toContain('scalar DateTime')
        ->toContain('scalar Date')
        ->toContain('scalar Mixed');
});

it('exposes the generated queries and mutations', function () {
    $schema = printGeneratedSchema();

    expect($schema)
        ->toContain('article(id: ID, slug: String): Article')
        ->toContain('articles(')
        ->toContain('publishedArticles(')
        ->toContain('paginatedArticles(')
        ->toContain('minViews: Int')
        ->toContain('status: String')
        ->toContain('articleBySlug(slug: String!): Article')
        ->toContain('article_queries(id: ID): Article')
        ->toContain('createArticle(input: ArticleInput!): Article')
        ->toContain('updateArticle(id: ID!, input: ArticleInput!): Article')
        ->toContain('deleteArticle(id: ID!): Article')
        ->toContain('archiveArticleMutations(id: ID!, status: String!): Article')
        ->toContain('purgeArticleMutations(id: ID!): Article')
        ->toContain('graphql(id: ID): [String!]');
});

it('exposes the generated fields, relations and overrides of a model', function () {
    $schema = printGeneratedSchema();

    expect($schema)
        ->toContain('meta: String')
        ->toContain('is_active: Boolean!')
        ->toContain('views: Int!')
        ->toContain('user: User')
        ->toContain('comments: [Comment]')
        ->toContain('tags: [Tag]')
        ->toContain('profile: Profile')
        ->toContain('morphComments: [Comment]')
        ->toContain('userComments: [Comment]')
        ->toContain('userProfile: Profile')
        ->toContain('status_label: String!')
        // Hidden columns never make it into the schema.
        ->not->toContain('internal_notes');
});

it('exposes the restricted scout filters inputs', function () {
    $schema = printGeneratedSchema();

    expect($schema)
        ->toContain('input QuerySearchablePostsScoutSearchScoutFilters')
        ->toContain('enum QuerySearchablePostsScoutSearchColumn')
        ->toContain('input QueryEnumColumnPostsScoutSearchScoutFilters')
        ->toContain('column: ArticleStatus')
        ->toContain('operator: MeilisearchOperator = EQ');
});

it('exposes the relation and input arguments added through attribute overrides', function () {
    $schema = printGeneratedSchema();

    // input_override added `published_at` even though it is not fillable.
    expect($schema)
        ->toContain('published_at: DateTime')
        // filters_override added `slug` to the single query and `minViews` to the collection.
        ->toContain('slug: String')
        ->toContain('minViews: Int');
});

it('keeps the shared order by clause type unless a collection opts in', function () {
    $schema = printGeneratedSchema();

    // `@orderBy(relations: ...)` makes Lighthouse generate a clause type per field, which
    // renames the argument type of that collection, so only `comments` opts in.
    expect($schema)
        ->toContain('orderBy: [OrderByClause!]')
        ->toContain('orderBy: [QueryCommentsOrderByRelationOrderByClause!]')
        ->not->toContain('orderBy: [QueryPublishedArticlesOrderByRelationOrderByClause!]');
});

it('builds an executable schema', function () {
    $schema = app(SchemaBuilder::class)->schema();

    expect($schema->getQueryType())->not->toBeNull()
        ->and($schema->getQueryType()->hasField('publishedArticles'))->toBeTrue()
        ->and($schema->getType('Article'))->not->toBeNull()
        ->and($schema->getType('ArticlePaginator'))->not->toBeNull()
        ->and($schema->getType('ScoutFilters'))->not->toBeNull()
        ->and($schema->getType('MeilisearchOperator'))->not->toBeNull();
});

it('reports duplicate directive definitions when validating the schema', function () {
    // NOTE: LaraQL appends the SDL definitions of @whereConditions and
    // @whereHasConditions, while Lighthouse's WhereConditions provider registers the
    // same directives. `lighthouse:validate-schema` injects the registered definitions
    // on top of the parsed schema and therefore reports both as defined twice.
    expect(fn () => Artisan::call('lighthouse:validate-schema'))
        ->toThrow(InvariantViolation::class, 'Directive @whereConditions defined multiple times');
});
